### ISSUE TITLE
Find area code prefixes that are not a US state or territory

### ISSUE THREAD

**Issue by claesmk** [NCATComp410/comp410_spring_2023#28]
Develop a function to detect area code prefixes in the [csv file](https://github.com/NCATComp410/comp410_spring_2023/blob/main/data.csv) that are not US states and territories, that is, are not in the list specified in [get_state_abbrev_freq](https://github.com/NCATComp410/comp410_spring_2023/blob/7fcdf82bc8f0807420e48728c353318e8080b56b/project.py#L116). Return these area codes as a list.

Expected Output:
```
[487, 522, 652, 642, 784, 591, 880, 348, 933, 987, 627, 893, 595, 866, 211, 328, 766, 969, 544, 995, 492, 421, 381, 249, 594, 482, 494, 596, 889, 932, 411, 696, 789, 922, 900, 902, 358, 871, 388, 550]
```

**Comment by Jmozebo93** [comment]
Good evening @claesmk 
we are almost done with the project, but it seems there is an issue with the expected output you have provided. In 'data.csv' file there are phone numbers with duplicate area codes that are not a US state or territory. For example, the phone numbers that start with 627 area code. When we print our output, it comes out according to the 'data.csv' . Should we assume that in your expected output you took care of duplicate or is it an error on your hand?

Regards;

**Comment by claesmk** [comment]
@Jmozebo93 I used my get_state_from_area_code() function when I implemented this, so it would remove any duplicated area codes.  The requirements were not specific about how to handle duplicates, so either way is OK.

**Comment by Jmozebo93** [comment]
Oh okay, thank you.
