### ISSUE TITLE
email domains and unique user counts

### ISSUE THREAD

**Issue by claesmk** [NCATComp410/comp410_spring_2023#5]
Create a function which inputs a comma separated list of email addresses and returns a dict with each email domain found and the total number of unique users.

- The keys should be the email domain, the values should be the total unique users
- Sort the dictionary alphabetically by email domain.
- Be sure to handle variable spacing around the comma.
- In the case of an invalid email address, raise a ValueError exception.

For example:

Input text
```
text = 'joe@gmail.com, john@outlook.com , jerry@abc.com,julie@xyz.com, tim@abc.com, joe@gmail.com'
```

Expected results
```
{'abc.com':2, 'gmail.com':1, 'outlook.com':1, 'xyz.com':1}
```

**Comment by Mbutle3** [comment]
y’all free to meet Thursday, Friday, or Saturday to work on this?

@naruto11236 @DanielHastie @lb-ali

**Comment by claesmk** [comment]
I'll give you two hints:

Correcting a mistake in a comment from last night:
1. The first requirement is to count UNIQUE users, your code is currently counting ALL users.  The Expected results for the Input text is actually correct - joe@gmail.com should only be counted once.  So, you could create another [object](https://developers.google.com/edu/python/lists) to track which users have already been seen for each domain. Sorry for any confusion here.
2. The requirement was to handle variable spacing around the comma.  Python has a string function called strip() which will strip leading and trailing spaces.  Try something like this:
```
    for email in list_of_emails:
        email_domain = email.split('@')[1].strip()
```
However, you'll probably want to do something like this since you need to count UNIQUE users
```
    for email in list_of_emails:
        user, email_domain = email.strip().split('@')
```

**Comment by DanielHastie** [comment]
Adding Updates
